### ISSUE TITLE
First Site Location is expanded by default

### ISSUE THREAD

**Issue by mwenger1** [mwenger1/clinical-trial-finder#58]
Problem: It might not be obvious that a site location can be clicked into, thus hiding the important email and phone number.

Solution: Expand the first option on page load. 

<img width="659" alt="screen shot 2016-09-05 at 10 03 45 pm" src="https://cloud.githubusercontent.com/assets/1781967/18259690/cb1bd330-73b4-11e6-97b1-2640784e8270.png">

**Comment by mwenger1** [comment]
@opihana WDUT?

**Comment by opihana** [comment]
@mwenger1 What brought this problem to your attention? Have you considered/done user testing before making a UI change like this? If the functionality isn't obvious, perhaps a different UI element would work better instead. For example, instead of an arrow, a link to "expand" or "show details". Making the entire row clickable with a UI change on hover would also indicate the toggle functionality.

**Comment by mwenger1** [comment]
There's no existing testing to guide our decision here.

The initial challenge was that some trials have 30+ sites and it creates a very long overwhelming scroll. All of the details for most of the sites are irrelevant except for a few of the closest ones.

I thought it made sense to highlight enough information to make a user say "I am interested in contacting this site based on it's location and/or the facility". They would then click in to get the contact details which includes email/phone/person's name.

It would definitely be problematic if someone came to this page and didn't realize that a site was expandable. A UI update like your learn more solution could be a good way to address that concern.

A few other changes that could improve these links:

1) List the facility name in addition to the city,state.
2) Change the styling of "5 miles away" so there's a UI break between the location, and the distance
